apiVersion: v1
kind: ReplicationController
metadata:
  name: etherquery-controller
spec:
  replicas: 1
  selector:
    app: etherquery
  template:
    metadata:
      labels:
        app: etherquery
    spec:
      containers:
      - name: etherquery
        image: ethereum/client-go
        ports:
        - containerPort: 8545
          name: json-rpc
        args: ["--rpc", "--rpcaddr", "0.0.0.0", "--datadir", "/mnt/blockchain"]
        volumeMounts:
        - name: ethereum-blockchain
          mountPath: "/mnt/blockchain"
      volumes:
      - name: ethereum-blockchain
        gcePersistentDisk:
          pdName: ethereum-blockchain
          fsType: ext4
